name: Continuous Integration
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses: Poornachandra3/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-frontend
      npm_install: false
    secrets: inherit




