name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-continuous-integration-reusable:
    uses: Poornachandra3/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-frontend
      npm_install: false
      release_archive_file: "public src"
    secrets: inherit




